
// ⚠️ Auto-generated by generateStory.ts
import { Button } from './Button';
import type { Meta, StoryObj } from '@storybook/react';

const meta: Meta<typeof Button> = {
  title: 'Components/Button',
  component: Button,
  tags: ["autodocs"],
  argTypes: {
  "label": {
    "control": "text"
  },
  "colour": {
    "control": {
      "type": "radio"
    },
    "options": [
      "primary",
      "success",
      "warning",
      "danger"
    ]
  },
  "variant": {
    "control": {
      "type": "radio"
    },
    "options": [
      "solid",
      "bordered",
      "faded",
      "light",
      "ghost",
      "shadow"
    ]
  },
  "isLoading": {
    "control": "boolean"
  },
  "size": {
    "control": {
      "type": "radio"
    },
    "options": [
      "sm",
      "md",
      "lg"
    ]
  }
},
};

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
  "label": "Click me",
  "colour": "primary",
  "variant": "solid",
  "isLoading": false,
  "size": "sm"
},
};
