
// ⚠️ Auto-generated by generateStory.ts
import { NestedNav } from './NestedNav';
import type { Meta, StoryObj } from '@storybook/react';

const meta: Meta<typeof NestedNav> = {
  title: 'Components/NestedNav',
  component: NestedNav,
  tags: ["autodocs"],
  argTypes: {},
};

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    menuTitle: "Menu",
    navItems: [
    { id: "1", label: 'Home', link: '#home' },
    {
      id: "2",
      label: 'Products',
      children: [
        { id: "21", label: 'Electronics', link: '#electronics' },
        { id: "22", label: 'Clothing', link: '#clothing' },
        {
          id: "23",
          label: 'Home & Garden',
          children: [
            { id: "231", label: 'Furniture', link: '#furniture' },
            { id: "232", label: 'Decor', link: '#decor' },
            { id: "233", label: 'Garden Tools', link: '#garden' }
          ]
        }
      ]
    },
    {
      id: "3",
      label: 'Services',
      children: [
        { id: "31", label: 'Consulting', link: '#consulting' },
        { id: "32", label: 'Support', link: '#support' }
      ]
    },
    { id: "4", label: 'About', link: '#about' },
    { id: "5", label: 'Contact', link: '#contact' }
  ]
  },
};
