
// ⚠️ Auto-generated by generateStory.ts
import { HeroBanner } from './HeroBanner';
import type { Meta, StoryObj } from '@storybook/react';

const meta: Meta<typeof HeroBanner> = {
  title: 'Components/HeroBanner',
  component: HeroBanner,
  tags: ["autodocs"],
  argTypes: {
  "title": {
    "control": "text"
  },
  "body": {
    "control": "text"
  }
},
};

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
  "title": "Lorem Ipsum",
  "body": "Lorem Ipsum",
  "button": {
      "label": "Click me",
      "colour": "primary",
      "size": "lg"
  },
  "image": {
    src: "https://images.unsplash.com/photo-1551434678-e076c223a692?w=800&h=600&fit=crop",
    alt: "Hero image"
  }
},
};
