
// ⚠️ Auto-generated by generateStory.ts
import Icon from './Icon';
import type { Meta, StoryObj } from '@storybook/react';

const meta: Meta<typeof Icon> = {
  title: 'Components/Icon',
  component: Icon,
  tags: ["autodocs"],
  argTypes: {},
};

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
      "color": "#ff40ff",
      "icon": "FaWalking",
      "size": 240
  },
};