
// ⚠️ Auto-generated by generateStory.ts
import { TextBlock } from './TextBlock';
import type { Meta, StoryObj } from '@storybook/react';

const meta: Meta<typeof TextBlock> = {
  title: 'Components/TextBlock',
  component: TextBlock,
  tags: ["autodocs"],
  argTypes: {},
};

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    value: [
      {
        _type: "block",
        children: [
          {
            _type: "span",
            text: "This is a simple text block.",
            marks: []
          },
        ],
      }
    ],
  }
};

export const WithIcon: Story = {
    args: {
    value: [
      {
        _type: "block",
        children: [
          {
            _type: "span",
            text: "This text has an icon ",
            marks: []
          },
          {
            _type: "span",
            text: "inline",
            marks: ["iconMark1"]
          },
        ],
        markDefs: [
          {
            _key: "iconMark1",
            _type: "icon",
            iconLibrary: "md",
            iconName: "MdCheck"
          },
        ]
      }
    ],
  }
}

export const WithExternalLink: Story = {
    args: {
    value: [
      {
        _type: "block",
        children: [
          {
            _type: "span",
            text: "This text is an external link ",
            marks: ["link1"]
          },
        ],
        markDefs: [
          {
              _key: "link1",
              _type: "link",
              internalLink: {
                _ref: "b0c3d4bb-2390-454a-9c04-35b3e1b6e3df",
                _type: "reference"
              },
              linkType: "external",
              externalUrl: "https://www.google.com"
            }
        ]
      }
    ],
  }
}

export const WithInternalLink: Story = {
  args: {
    value: [
      {
        _type: "block",
        children: [
          {
            _type: "span",
            text: "This text is an internal link ",
            marks: ["link1"]
          },
        ],
        markDefs: [
          {
              _key: "link1",
              _type: "link",
              internalLink: {
                _ref: "b0c3d4bb-2390-454a-9c04-35b3e1b6e3df",
                _type: "reference"
              },
              internalUrl: "/about-us",
              linkType: "internal",
            }
        ]
      }
    ],
  }
}
