
// ⚠️ Auto-generated by generateStory.ts
import { TextBlock } from './TextBlock';
import type { Meta, StoryObj } from '@storybook/react';

const meta: Meta<typeof TextBlock> = {
  title: 'Components/TextBlock',
  component: TextBlock,
  tags: ["autodocs"],
  argTypes: {},
};

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    value: [
      {
        _type: "block",
        children: [
          {
            _type: "span",
            text: "This text has an icon ",
            marks: []
          },
          {
            _type: "span",
            text: "inline",
            marks: ["iconMark1"]
          }
        ],
        markDefs: [
          {
            _key: "iconMark1",
            _type: "icon",
            iconLibrary: "md",
            iconName: "MdCheck"
          }
        ]
      }
    ]
  }
};

