
// ⚠️ Auto-generated by generateStory.ts
import { Breadcrumbs } from './Breadcrumbs';
import type { Meta, StoryObj } from '@storybook/react';

const meta: Meta<typeof Breadcrumbs> = {
  title: 'Components/Breadcrumbs',
  component: Breadcrumbs,
  tags: ["autodocs"],
  argTypes: {},
};

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    items: [
      {
      href: "/home",
      body: "Home"
    },
    {
      href: "/page",
      body: "Page"
    },
    {
      href: "/child",
      body: "Child"
    }
  ]
  },
};
